name: CI

on:
  # We run CI on pushes to the main branch
  push:
    branches:
      - main
  # and on all pull requests to the main branch
  pull_request:
    branches:
      - main
  # as well as upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-and-test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # setuptools_scm requires a non-shallow clone of the repository
        fetch-depth: 0

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Python package
      run: |
        python -m pip install .[tests]

    - name: Run Python tests
      run: |
        python -m pytest
